myapp-backend:
  env:
    - name: HOST
      value: h8r.dev
    - name: ENV_NAME
      value: main-env
  fullnameOverride: myapp-backend
  image:
    repository: ghcr.io/jack230230/myapp-backend
    tag: af2cfcf
  imagePullSecrets:
    - name: myapp-docker
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    className: nginx
    enabled: true
    hosts:
      - host: myapp.h8r.site
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
          - path: /v2/api(/|$)(.*)
            pathType: ImplementationSpecific
  nocalhost:
    command:
      debug: dlv --headless --log --listen :9009 --api-version 2 --accept-multiclient debug main.go
      run: air
    configPath: conf/nocalhost.yaml
    env:
      - name: GOCACHE
        value: /go/.cache
    gitURL: https://github.com/jack230230/myapp-backend.git
    hotReload: false
    image: ghcr.io/jack230230/myapp-backend
    language: go
    persistentVolumeDirs:
      - capacity: 20Gi
        path: /home/nocalhost-dev
      - capacity: 20Gi
        path: /go
    remoteDebugPort: 9009
  service:
    targetPort: 8000
myapp-frontend:
  env:
    - name: HOST
      value: h8r.dev
    - name: ENV_NAME
      value: main-env
  fullnameOverride: myapp-frontend
  image:
    repository: ghcr.io/jack230230/myapp-frontend
    tag: 772d4a7
  imagePullSecrets:
    - name: myapp-docker
  ingress:
    className: nginx
    enabled: true
    hosts:
      - host: myapp.h8r.site
        paths:
          - path: /
            pathType: ImplementationSpecific
  nocalhost:
    command:
      debug: npm install && npm run dev
      run: npm install && npm run dev
    configPath: conf/nocalhost.yaml
    env: null
    gitURL: https://github.com/jack230230/myapp-frontend.git
    hotReload: false
    image: ghcr.io/jack230230/myapp-frontend
    language: typescript
    persistentVolumeDirs:
      - capacity: 20Gi
        path: /home/nocalhost-dev
    remoteDebugPort: 9009
  service:
    targetPort: 3000
